---
- hosts: ssdnodes
  remote_user: root
  vars:
    jupyter_domain: dev.jitsejan.com
    jupyter_name: 'dev'
    jupyter_port: 8181
    key_out: /home/jupyter/.jupyter/jupyter.key
    cert_out: /home/jupyter/.jupyter/jupyter.cert
  vars_prompt:
    - name: "user_name"
      prompt: "Enter a name for the new user"
      private: no
      confirm: no
    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
  roles:
  - base
  - common
  - {
      role: 'spark',
      spark_version: '2.4.4',
      hadoop_version: '3.1.2',
      aws_version: '1.11.534'
  }
  - jupyter
  - {
      role: 'nginx',
      app_ip: localhost,
    }
  - {
    role: 'minio',
    minio_server_datadirs: [
      '/minio-data/'
    ],
    minio_server_download_url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
  }