jupyter_pkgs:
  - git
  - npm
  - python
  - python-dev
  - python-setuptools
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - sudo
  - apt-transport-https

# Jupyter
jupyter_config_filename: '/home/jupyter/.jupyter/jupyterhub_config.py'
ssl_country: UK
ssl_state: GL
ssl_city: LDN
ssl_org: JJ