---
- name: Install letsencrypt
  apt: 
    name: letsencrypt
    state: latest
- name: Create letsencrypt certificate
  shell: letsencrypt certonly --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ jupyter_domain }}
  args:
    creates: /etc/letsencrypt/live/{{ jupyter_domain }}
- name: Change file ownership, group and permissions
  file:
    path: /etc/letsencrypt/live/{{ jupyter_domain }}
    owner: jupyter
    group: jupyter
    mode: '0644'